### ISSUE TITLE
"Debug Spell" Drop

### ISSUE THREAD

**Issue by giova-01** [WinDanesz/mo-spells#3]
I want to add this mod to a magic-based modpack for my friends, but when i kill any mob from mowzie's mobs, the spell that is droped is a sort of "Debug spell", instead of a random usable spell. Here is a screenshot:
![2021-09-24_19 15 54](https://user-images.githubusercontent.com/80795034/134745675-ee0ac30d-95ab-434f-8fab-e7b59c125879.png)

i have 4 addons, appart from Mowzie's mobs and ebwizardry:
-Zettai Magic
-Zettai Grimories 
-Ancient Spellcraft
-Extra Spells

i tried injecting the spells in the creeper loot table with the configs, but i was given the same debug spell again.

**Comment by WinDanesz** [comment]
You haven't provided the mod version numbers

**Comment by giova-01** [comment]
My bad, its 1.12.2 - 1.0.1, i didnt realized you updated the mod 4 days ago in curseforge. Gonna update now, thanks for the amazing mod!

**Comment by giova-01** [comment]
The bug is fixed in v1.0.2, closing the issue.
